server:
  port: 8080

#spring:
#  datasource:
#    url: [Postgres Database]
#    username: ls_admin
#    password: location
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    generate-ddl: false
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#    properties:
#      hibernate:
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
#        temp:
#          use_jdbc_metadata_defaults: false

#Comment out below for to erase h2
spring:  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
    initialize: true
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: true
      
      
  

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka